In [179]:
print(" What are data types in Python")

 What are data types in Python


In [180]:
Data_type = {
    'Logical': ['bool'],
'Numeric': ['int' , 'float'],
'Text': ['str']
}
print (Data_type)

{'Logical': ['bool'], 'Numeric': ['int', 'float'], 'Text': ['str']}


In [181]:
print(" What are data structures in Python")

 What are data structures in Python


In [182]:

Data_Structure = ['list', 'tuple', 'dictionary' ,'set']

print(Data_Structure)

['list', 'tuple', 'dictionary', 'set']


In [183]:
################# Excercise 1############################
# create a vector as array
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


In [184]:
# Creating List
l = ("vimal" , 1,2)
print (l)

('vimal', 1, 2)


In [185]:
import numpy as np
# New Vector
a = np.array([0, 1, 2])
print(type(a))
#Shape of vector
print(a.shape)
##Print an element
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
[5 1 2]


In [186]:
#Size of vector
print(a.size)

3


In [187]:
# List addition (concatenation)
l2 = ("kumar" , 4 ,5)
print(l + l2)

('vimal', 1, 2, 'kumar', 4, 5)


In [188]:
# Vector Addition
a2 = np.array([3,4,5])
print (a + a2)

[8 5 7]


In [189]:
################# Excercise 2############################
# Matrice addition
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
# Elementwise sum; both produce the array
print(x+y)
print(np.add(x, y)) #Same result of +
# Elementwise difference; both produce the array
print(x-y)
print(np.subtract(x, y)) #Same result of -


[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [222]:
#Multiplication
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
  

res = np.dot(mat1,mat2) 
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [191]:
#Transpose of x
print(x.T)

[[1 3 5]
 [2 4 6]]


In [217]:
A = np.array([[1, 2],[3,4]])
print("The Matrix A \n",A)
print("The dimension of A \n ",A.shape)
Inverse = np.linalg.inv(A)

print ("Inverse is \n ",Inverse)


The Matrix A 
 [[1 2]
 [3 4]]
The dimension of A 
  (2, 2)
Inverse is 
  [[-2.   1. ]
 [ 1.5 -0.5]]


In [193]:
#####################Excercise 3.1############################
# Identical Matirix

a = [     
        [1, 2, 3],  
        [8, 4, 6],  
        [4, 5, 7]  
    ];  
   
#Initialize matrix b  
b = [     
        [1, 2, 3],  
        [8, 4, 6],  
        [4, 5, 7]  
    ];  
   
flag = True;  
   
#Calculates number of rows and columns present in first matrix  
row1 = len(a);  
col1 = len(a[0]);  
   
#Calculates number of rows and columns present in second matrix  
row2 = len(b);  
col2 = len(b[0]);  
   
#Checks if dimensions of both the matrices are equal  
if(row1 != row2 or col1 != col2):  
    print("Matrices are not equal");  
   
else:  
    for i in range(0, row1):  
        for j in range(0, col1):  
            if(a[i][j] != b[i][j]):  
                flag = False;  
                break;  
      
    if(flag):  
        print("Matrices are equal");  
    else:  
        print("Matrices are not equal");  


Matrices are equal


In [194]:
#####################Excercise 3.2############################
# Mirror Matrix

a = [     
        [1, 2, 3],  
        [8, 4, 6],  
        [4, 5, 7]  
    ];  
   
#Initialize matrix b  
b = [     
        [3, 2, 1],  
        [6, 4, 8],  
        [7, 5, 4]  
    ];  
   
flag = True;  
   
#Calculates number of rows and columns present in first matrix  
row1 = len(a);  
col1 = len(a[0]);  
   
#Calculates number of rows and columns present in second matrix  
row2 = len(b);  
col2 = len(b[0]);  
   
#Checks if dimensions of both the matrices are equal  
if(row1 != row2 or col1 != col2):  
    print("Matrices are not mirrored");  
   
else:  
    for i in range(0, row1):  
        for j in range(0 , col1):  
             #Condition for mirroring
            if(a[i][j] != b[i][row1- j -1]):
                print (a[i][j] , b[i][col1- j - 1])
                flag = False;  
                break;  
      
    if(flag):  
        print("Matrices are mirrored");  
    else:  
        print("Matrices are not mirrored");  


Matrices are mirrored


In [195]:
import pandas as pd
df=pd.read_csv('dslab2.csv')
print(df)

  Student   Marks out of 100
0    Vimal               100
1    Khaju               -10
2    Manas               200
3     Guru                35


In [196]:
df.head()

Student   Marks out of 100
0    Vimal               100
1    Khaju               -10
2    Manas               200
3     Guru                35

In [197]:
df.shape


(4, 2)

In [198]:
df.dtypes

Student             object
Marks out of 100     int64
dtype: object

In [199]:
#JSON similar object 
mobile_data = {
    'Phone' : ['iPhone 11' , 'Samsung 10' , 'One plus 8'],
    'Cost' : ['1000', '800', '700'],
    'RAM in GB':['4', '6', '6']
}

In [200]:
Write_DF = pd.DataFrame(mobile_data)
Write_DF.head()

Phone  Cost RAM in GB
0   iPhone 11  1000         4
1  Samsung 10   800         6
2  One plus 8   700         6

In [201]:
#### Exporting & reading exported CSV
Write_DF.to_csv('writeToCSV.csv')
Write_DF.head()

Phone  Cost RAM in GB
0   iPhone 11  1000         4
1  Samsung 10   800         6
2  One plus 8   700         6